MVC/Practice/API/Library-app/BookAuthorWebAPI/BookAuthorWebAPI/Controllers/BookController.cs
using BookAuthorWebAPI.Models;
using BookAuthorWebAPI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace BookAuthorWebAPI.Controllers
{
    public class BookController : Controller
    {
        private static readonly HttpClient client = new HttpClient();

        public async Task<ActionResult> Index()
        {
            var json = await client.GetStringAsync("https://localhost:7106/api/Book");
            var books = JsonConvert.DeserializeObject<List<Book>>(json);

            return View(books);
        }
        public async Task<ActionResult> AddBook()
        {
            return View();
        }

        public async Task<ActionResult> AddBook(Book book)
        {
            var json = JsonConvert.SerializeObject(book);
            var content = new StringContent(json, Encoding.UTF8, "application/Json");

            var response = await client.PostAsync(client.GetStringAsync("https://localhost:7106/api/Book").ToString(), content);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(book);
            }
        }
    }
}

MVC/Practice/API/Library-app/BookAuthorWebAPI/BookAuthorWebAPI/Controllers/UserController.cs
using BookAuthorWebAPI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BookAuthorWebAPI.Controllers
{
    public class UserController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        public UserController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public IActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignIn(SignInUser signInUser)
        {
            HttpClient httpClient = _httpClientFactory.CreateClient();
            HttpResponseMessage responseMessage = await httpClient.PostAsJsonAsync("https://localhost:7106/api/Login", signInUser);
            if (responseMessage.IsSuccessStatusCode)
            {
                // API'den dönen token ve son kullanma süresi bilgilerini al
                var tokenResponse = await responseMessage.Content.ReadAsStringAsync();
                var tokenObject = JsonConvert.DeserializeObject<Dictionary<string, string>>(tokenResponse);
                var token = tokenObject["token"];
                var expires = tokenObject["expires"];

                // Token'ı saklamak için uygun bir yöntem kullanabilirsiniz, örneğin session kullanabilirsiniz
                HttpContext.Session.SetString("JwtToken", token);
                return View();
            }
            else
            {
                return BadRequest();
            }

        }
    }
}

MVC/Practice/API/Library-app/BookAuthorWebAPI/BookAuthorWebAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookAuthorWebAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookAuthorWebAPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookAuthorWebAPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">List Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">List Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TypeOfBook" asp-action="Index">List TypeOfBooks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignIn">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookAuthorWebAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>